-- =====================================================
-- ESQUEMA DE BASE DE DATOS - SISTEMA SUPERMERCADO
-- Compatible con PostgreSQL y Supabase
-- Versión: 1.0.0
-- Fecha: 2025-12-30
-- =====================================================

-- ==================== FUNCIÓN PARA TIMESTAMPS ====================
CREATE OR REPLACE FUNCTION actualizar_modified_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.modified_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==================== TABLA: CLIENTES ====================
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente VARCHAR(100) NOT NULL,
    nit_cliente VARCHAR(50) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_nit_cliente UNIQUE (nit_cliente)
);

CREATE TRIGGER trigger_actualizar_modified_at
    BEFORE UPDATE ON clientes
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: NEGOCIOS ====================
CREATE TABLE IF NOT EXISTS negocios (
    id_negocio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    nombre_negocio VARCHAR(100) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_negocios_cliente FOREIGN KEY (id_cliente) 
        REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_negocios
    BEFORE UPDATE ON negocios
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: REMISIONES ====================
CREATE TABLE IF NOT EXISTS remisiones (
    remision_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_remision INT NOT NULL,
    id_cliente INT NOT NULL,
    fecha DATE NOT NULL,
    estado_remision VARCHAR(50) NOT NULL,
    valor_remsion INT NOT NULL,
    nombre_negocio VARCHAR(255),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_numero_remision UNIQUE (numero_remision),
    CONSTRAINT fk_remisiones_cliente FOREIGN KEY (id_cliente) 
        REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_remisiones
    BEFORE UPDATE ON remisiones
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: FACTURAS ====================
CREATE TABLE IF NOT EXISTS facturas (
    factura_id SERIAL PRIMARY KEY,
    numero_factura VARCHAR(50) NOT NULL,
    id_cliente INT NOT NULL,
    fecha DATE NOT NULL,
    estado_factura VARCHAR(50) NOT NULL,
    valor_factura INT NOT NULL,
    balance_factura NUMERIC(15,2),
    nombre_negocio VARCHAR(255),
    prefijo VARCHAR(20),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_numero_factura UNIQUE (numero_factura),
    CONSTRAINT fk_facturas_cliente FOREIGN KEY (id_cliente) 
        REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_facturas
    BEFORE UPDATE ON facturas
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: EMPLEADOS ====================
CREATE TABLE IF NOT EXISTS empleados (
    id_empleado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empleado VARCHAR(100) NOT NULL,
    tipo_documento VARCHAR(100) NOT NULL,
    cedula_empleado VARCHAR(50) NOT NULL,
    salario_dia INT NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_cedula_empleado UNIQUE (cedula_empleado)
);

CREATE TRIGGER trigger_actualizar_modified_at_empleados
    BEFORE UPDATE ON empleados
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: TURNOS ====================
CREATE TABLE IF NOT EXISTS turnos (
    id_turno INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado INT NOT NULL,
    hora_inicio TIMESTAMP,
    hora_salida TIMESTAMP,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_turnos_empleado FOREIGN KEY (id_empleado) 
        REFERENCES empleados(id_empleado) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_turnos
    BEFORE UPDATE ON turnos
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: USUARIOS ====================
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    es_master BOOLEAN DEFAULT FALSE,
    es_admin BOOLEAN DEFAULT FALSE,
    es_empleado BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_username UNIQUE (username)
);

CREATE TRIGGER trigger_actualizar_modified_at_usuarios
    BEFORE UPDATE ON usuarios
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: MODULOS DEL SISTEMA ====================
CREATE TABLE IF NOT EXISTS modulos_sistema (
    id_modulo SERIAL PRIMARY KEY,
    nombre_modulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200),
    icono VARCHAR(50),
    orden INT DEFAULT 0
);

-- ==================== TABLA: PERMISOS USUARIOS-MODULOS ====================
CREATE TABLE IF NOT EXISTS usuarios_modulos (
    id_usuario INT NOT NULL,
    id_modulo INT NOT NULL,
    puede_ver BOOLEAN DEFAULT TRUE,
    puede_editar BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id_usuario, id_modulo),
    CONSTRAINT fk_um_usuario FOREIGN KEY (id_usuario) 
        REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_um_modulo FOREIGN KEY (id_modulo) 
        REFERENCES modulos_sistema(id_modulo) ON DELETE CASCADE
);

-- ==================== TABLA: DIRECCIONES IP AUTORIZADAS ====================
CREATE TABLE IF NOT EXISTS direcciones_ip (
    id_direccion SERIAL PRIMARY KEY,
    direccion_ip VARCHAR(45) NOT NULL,
    nombre_equipo VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_direccion_ip UNIQUE (direccion_ip)
);

CREATE TRIGGER trigger_actualizar_modified_at_ip
    BEFORE UPDATE ON direcciones_ip
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== DATOS INICIALES ====================

-- Módulos del sistema
INSERT INTO modulos_sistema (nombre_modulo, descripcion, icono, orden) VALUES
    ('Cartera', 'Gestión de cartera de clientes', 'wallet2', 1),
    ('Empleados', 'Gestión de empleados y turnos', 'people', 2),
    ('Configuración', 'Configuración del sistema', 'gear', 3),
    ('Nómina', 'Gestión de nómina y pagos', 'cash-stack', 4)
ON CONFLICT DO NOTHING;

-- =====================================================
-- NOTA: El usuario master inicial debe ser creado 
-- manualmente o mediante la aplicación.
-- 
-- Para crear un usuario master desde SQL:
-- 
-- INSERT INTO usuarios (username, password_hash, nombre_completo, es_master, activo)
-- VALUES ('admin', '<SHA256_HASH_DE_PASSWORD>', 'Administrador', TRUE, TRUE);
--
-- Luego asignar todos los módulos:
-- INSERT INTO usuarios_modulos (id_usuario, id_modulo, puede_ver, puede_editar)
-- SELECT 1, id_modulo, TRUE, TRUE FROM modulos_sistema;
-- =====================================================

-- ==================== ÍNDICES ADICIONALES (OPCIONALES) ====================
CREATE INDEX IF NOT EXISTS idx_remisiones_cliente ON remisiones(id_cliente);
CREATE INDEX IF NOT EXISTS idx_remisiones_fecha ON remisiones(fecha);
CREATE INDEX IF NOT EXISTS idx_remisiones_estado ON remisiones(estado_remision);

CREATE INDEX IF NOT EXISTS idx_facturas_cliente ON facturas(id_cliente);
CREATE INDEX IF NOT EXISTS idx_facturas_fecha ON facturas(fecha);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON facturas(estado_factura);

CREATE INDEX IF NOT EXISTS idx_turnos_empleado ON turnos(id_empleado);
CREATE INDEX IF NOT EXISTS idx_turnos_fecha ON turnos(hora_inicio);

CREATE INDEX IF NOT EXISTS idx_usuarios_activo ON usuarios(activo);
