-- =====================================================
-- ESQUEMA DE BASE DE DATOS - SISTEMA SUPERMERCADO
-- Compatible con PostgreSQL y Supabase
-- Versión: 1.0.0
-- Fecha: 2025-12-30
-- =====================================================

-- ==================== FUNCIÓN PARA TIMESTAMPS ====================
CREATE OR REPLACE FUNCTION actualizar_modified_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.modified_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==================== TABLA: CLIENTES ====================
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente VARCHAR(100) NOT NULL,
    nit_cliente VARCHAR(50) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_nit_cliente UNIQUE (nit_cliente)
);

CREATE TRIGGER trigger_actualizar_modified_at
    BEFORE UPDATE ON clientes
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: NEGOCIOS ====================
CREATE TABLE IF NOT EXISTS negocios (
    id_negocio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    nombre_negocio VARCHAR(100) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_negocios_cliente FOREIGN KEY (id_cliente) 
        REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_negocios
    BEFORE UPDATE ON negocios
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: REMISIONES ====================
CREATE TABLE IF NOT EXISTS remisiones (
    remision_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_remision INT NOT NULL,
    id_cliente INT NOT NULL,
    fecha DATE NOT NULL,
    estado_remision VARCHAR(50) NOT NULL,
    valor_remsion INT NOT NULL,
    nombre_negocio VARCHAR(255),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_numero_remision UNIQUE (numero_remision),
    CONSTRAINT fk_remisiones_cliente FOREIGN KEY (id_cliente) 
        REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_remisiones
    BEFORE UPDATE ON remisiones
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: FACTURAS ====================
CREATE TABLE IF NOT EXISTS facturas (
    factura_id SERIAL PRIMARY KEY,
    numero_factura VARCHAR(50) NOT NULL,
    id_cliente INT NOT NULL,
    fecha DATE NOT NULL,
    estado_factura VARCHAR(50) NOT NULL,
    valor_factura INT NOT NULL,
    balance_factura NUMERIC(15,2),
    nombre_negocio VARCHAR(255),
    prefijo VARCHAR(20),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_numero_factura UNIQUE (numero_factura),
    CONSTRAINT fk_facturas_cliente FOREIGN KEY (id_cliente) 
        REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_facturas
    BEFORE UPDATE ON facturas
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: SEDES ====================
CREATE TABLE IF NOT EXISTS sedes (
    id_sede INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_sede VARCHAR(100) NOT NULL,
    direccion VARCHAR(200),
    activo BOOLEAN DEFAULT TRUE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_nombre_sede UNIQUE (nombre_sede)
);

CREATE TRIGGER trigger_actualizar_modified_at_sedes
    BEFORE UPDATE ON sedes
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: ROLES ====================
CREATE TABLE IF NOT EXISTS roles (
    id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200),
    activo BOOLEAN DEFAULT TRUE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_nombre_rol UNIQUE (nombre_rol)
);

CREATE TRIGGER trigger_actualizar_modified_at_roles
    BEFORE UPDATE ON roles
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: EMPLEADOS ====================
CREATE TABLE IF NOT EXISTS empleados (
    id_empleado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sede INT,
    id_rol INT,
    nombre_empleado VARCHAR(100) NOT NULL,
    tipo_documento VARCHAR(100) NOT NULL,
    cedula_empleado VARCHAR(50) NOT NULL,
    celular VARCHAR(20),
    salario_dia INT NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_cedula_empleado UNIQUE (cedula_empleado),
    CONSTRAINT fk_empleados_sede FOREIGN KEY (id_sede)
        REFERENCES sedes(id_sede) ON DELETE SET NULL,
    CONSTRAINT fk_empleados_rol FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol) ON DELETE SET NULL
);

CREATE TRIGGER trigger_actualizar_modified_at_empleados
    BEFORE UPDATE ON empleados
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: TURNOS ====================
CREATE TABLE IF NOT EXISTS turnos (
    id_turno INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado INT NOT NULL,
    hora_inicio TIMESTAMP,
    hora_salida TIMESTAMP,
    foto_entrada BYTEA,
    foto_salida BYTEA,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_turnos_empleado FOREIGN KEY (id_empleado) 
        REFERENCES empleados(id_empleado) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_turnos
    BEFORE UPDATE ON turnos
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: TOTAL_HORAS ====================
CREATE TABLE IF NOT EXISTS total_horas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_turno INT NOT NULL,
    fecha DATE NOT NULL,
    total_horas DECIMAL(5,2) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_total_horas_turno FOREIGN KEY (id_turno) 
        REFERENCES turnos(id_turno) ON DELETE CASCADE,
    CONSTRAINT unique_id_turno_total_horas UNIQUE (id_turno)
);

CREATE TRIGGER trigger_actualizar_modified_at_total_horas
    BEFORE UPDATE ON total_horas
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

CREATE INDEX IF NOT EXISTS idx_total_horas_fecha ON total_horas(fecha);
CREATE INDEX IF NOT EXISTS idx_total_horas_turno ON total_horas(id_turno);

-- ==================== TABLA: HORAS_EXTRA ====================
CREATE TABLE IF NOT EXISTS horas_extra (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_turno INT NOT NULL,
    id_hora INT NOT NULL,
    total_horas_extra DECIMAL(5,2) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_horas_extra_turno FOREIGN KEY (id_turno) 
        REFERENCES turnos(id_turno) ON DELETE CASCADE,
    CONSTRAINT fk_horas_extra_hora FOREIGN KEY (id_hora) 
        REFERENCES total_horas(id) ON DELETE CASCADE,
    CONSTRAINT unique_id_turno_horas_extra UNIQUE (id_turno)
);

CREATE TRIGGER trigger_actualizar_modified_at_horas_extra
    BEFORE UPDATE ON horas_extra
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

CREATE INDEX IF NOT EXISTS idx_horas_extra_turno ON horas_extra(id_turno);
CREATE INDEX IF NOT EXISTS idx_horas_extra_hora ON horas_extra(id_hora);

-- ==================== TABLA: USUARIOS ====================
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    es_master BOOLEAN DEFAULT FALSE,
    es_admin BOOLEAN DEFAULT FALSE,
    es_empleado BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_username UNIQUE (username)
);

CREATE TRIGGER trigger_actualizar_modified_at_usuarios
    BEFORE UPDATE ON usuarios
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== TABLA: MODULOS DEL SISTEMA ====================
CREATE TABLE IF NOT EXISTS modulos_sistema (
    id_modulo SERIAL PRIMARY KEY,
    nombre_modulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200),
    icono VARCHAR(50),
    orden INT DEFAULT 0
);

-- ==================== TABLA: PERMISOS USUARIOS-MODULOS ====================
CREATE TABLE IF NOT EXISTS usuarios_modulos (
    id_usuario INT NOT NULL,
    id_modulo INT NOT NULL,
    puede_ver BOOLEAN DEFAULT TRUE,
    puede_editar BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id_usuario, id_modulo),
    CONSTRAINT fk_um_usuario FOREIGN KEY (id_usuario) 
        REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_um_modulo FOREIGN KEY (id_modulo) 
        REFERENCES modulos_sistema(id_modulo) ON DELETE CASCADE
);

-- ==================== TABLA: DIRECCIONES IP AUTORIZADAS ====================
CREATE TABLE IF NOT EXISTS direcciones_ip (
    id_direccion SERIAL PRIMARY KEY,
    direccion_ip VARCHAR(45) NOT NULL,
    nombre_equipo VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_direccion_ip UNIQUE (direccion_ip)
);

CREATE TRIGGER trigger_actualizar_modified_at_ip
    BEFORE UPDATE ON direcciones_ip
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- ==================== DATOS INICIALES ====================

-- Módulos del sistema
INSERT INTO modulos_sistema (nombre_modulo, descripcion, icono, orden) VALUES
    ('CXP Supermercado', 'Cuentas por pagar supermercado', 'wallet2', 1),
    ('Empleados', 'Gestión de empleados y turnos', 'people', 2),
    ('Configuración', 'Configuración del sistema', 'gear', 3),
    ('Nómina', 'Gestión de nómina y pagos', 'cash-stack', 4)
ON CONFLICT DO NOTHING;

-- Sedes de Kikes
INSERT INTO sedes (nombre_sede) VALUES
    ('Kikes Principal'),
    ('Kikes 2'),
    ('Kikes Pizza')
ON CONFLICT (nombre_sede) DO NOTHING;

-- Roles de empleados
INSERT INTO roles (nombre_rol, descripcion) VALUES
    ('Parrillero', 'Encargado de la parrilla'),
    ('Cocinero', 'Preparación de alimentos'),
    ('Cajero', 'Atención en caja'),
    ('Administrador', 'Gestión administrativa'),
    ('Domiciliario', 'Entregas a domicilio')
ON CONFLICT (nombre_rol) DO NOTHING;

-- =====================================================
-- NOTA: El usuario master inicial debe ser creado 
-- manualmente o mediante la aplicación.
-- 
-- Para crear un usuario master desde SQL:
-- 
-- INSERT INTO usuarios (username, password_hash, nombre_completo, es_master, activo)
-- VALUES ('admin', '<SHA256_HASH_DE_PASSWORD>', 'Administrador', TRUE, TRUE);
--
-- Luego asignar todos los módulos:
-- INSERT INTO usuarios_modulos (id_usuario, id_modulo, puede_ver, puede_editar)
-- SELECT 1, id_modulo, TRUE, TRUE FROM modulos_sistema;
-- =====================================================

-- ==================== ÍNDICES ADICIONALES (OPCIONALES) ====================
CREATE INDEX IF NOT EXISTS idx_remisiones_cliente ON remisiones(id_cliente);
CREATE INDEX IF NOT EXISTS idx_remisiones_fecha ON remisiones(fecha);
CREATE INDEX IF NOT EXISTS idx_remisiones_estado ON remisiones(estado_remision);

CREATE INDEX IF NOT EXISTS idx_facturas_cliente ON facturas(id_cliente);
CREATE INDEX IF NOT EXISTS idx_facturas_fecha ON facturas(fecha);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON facturas(estado_factura);

CREATE INDEX IF NOT EXISTS idx_turnos_empleado ON turnos(id_empleado);
CREATE INDEX IF NOT EXISTS idx_turnos_fecha ON turnos(hora_inicio);

CREATE INDEX IF NOT EXISTS idx_usuarios_activo ON usuarios(activo);

-- ==================== TABLA: DESCUENTOS NÓMINA ====================
CREATE TABLE IF NOT EXISTS descuentos_nomina (
    id_descuento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado INT NOT NULL,
    tipo_descuento VARCHAR(50) NOT NULL,
    detalle VARCHAR(255),
    valor NUMERIC(12,2) NOT NULL,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    id_liquidacion INT,
    pagado BOOLEAN DEFAULT FALSE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_descuentos_empleado FOREIGN KEY (id_empleado) 
        REFERENCES empleados(id_empleado) ON DELETE CASCADE
);

CREATE TRIGGER trigger_actualizar_modified_at_descuentos
    BEFORE UPDATE ON descuentos_nomina
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

CREATE INDEX IF NOT EXISTS idx_descuentos_empleado ON descuentos_nomina(id_empleado);
CREATE INDEX IF NOT EXISTS idx_descuentos_fecha ON descuentos_nomina(fecha);

-- ==================== TABLA: CONFIGURACIÓN NÓMINA ====================
CREATE TABLE IF NOT EXISTS configuracion_nomina (
    id_config INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_config VARCHAR(100) NOT NULL,
    valor_config DECIMAL(10,2) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_nombre_config UNIQUE (nombre_config)
);

CREATE TRIGGER trigger_actualizar_modified_at_config_nomina
    BEFORE UPDATE ON configuracion_nomina
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

-- Insertar configuración por defecto del descuento en comida (10%)
INSERT INTO configuracion_nomina (nombre_config, valor_config, descripcion)
VALUES ('descuento_comida_porcentaje', 10.00, 'Porcentaje de descuento aplicado a los consumos de alimento de los empleados')
ON CONFLICT (nombre_config) DO NOTHING;

-- ==================== TABLA: LIQUIDACIONES NÓMINA ====================
CREATE TABLE IF NOT EXISTS liquidaciones_nomina (
    id_liquidacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_liquidacion DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    total_bruto NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_descuentos NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_neto NUMERIC(15,2) NOT NULL DEFAULT 0,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    observaciones TEXT,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_actualizar_modified_at_liquidaciones
    BEFORE UPDATE ON liquidaciones_nomina
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

CREATE INDEX IF NOT EXISTS idx_liquidaciones_fecha ON liquidaciones_nomina(fecha_liquidacion);
CREATE INDEX IF NOT EXISTS idx_liquidaciones_estado ON liquidaciones_nomina(estado);

-- ==================== TABLA: DETALLE LIQUIDACIÓN POR EMPLEADO ====================
CREATE TABLE IF NOT EXISTS detalle_liquidacion (
    id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liquidacion INT NOT NULL,
    id_empleado INT NOT NULL,
    dias_trabajados INT NOT NULL DEFAULT 0,
    horas_trabajadas DECIMAL(8,2) NOT NULL DEFAULT 0,
    horas_extra DECIMAL(8,2) NOT NULL DEFAULT 0,
    salario_base NUMERIC(12,2) NOT NULL DEFAULT 0,
    valor_horas_extra NUMERIC(12,2) NOT NULL DEFAULT 0,
    subtotal_bruto NUMERIC(12,2) NOT NULL DEFAULT 0,
    descuento_comida_bruto NUMERIC(12,2) NOT NULL DEFAULT 0,
    porcentaje_descuento_comida DECIMAL(5,2) NOT NULL DEFAULT 0,
    descuento_comida_neto NUMERIC(12,2) NOT NULL DEFAULT 0,
    otros_descuentos NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_descuentos NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_neto NUMERIC(12,2) NOT NULL DEFAULT 0,
    ajuste_manual NUMERIC(12,2) DEFAULT 0,
    observaciones TEXT,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_detalle_liquidacion FOREIGN KEY (id_liquidacion) 
        REFERENCES liquidaciones_nomina(id_liquidacion) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_empleado FOREIGN KEY (id_empleado) 
        REFERENCES empleados(id_empleado) ON DELETE CASCADE,
    CONSTRAINT unique_liquidacion_empleado UNIQUE (id_liquidacion, id_empleado)
);

CREATE TRIGGER trigger_actualizar_modified_at_detalle_liquidacion
    BEFORE UPDATE ON detalle_liquidacion
    FOR EACH ROW
    EXECUTE FUNCTION actualizar_modified_at();

CREATE INDEX IF NOT EXISTS idx_detalle_liquidacion ON detalle_liquidacion(id_liquidacion);
CREATE INDEX IF NOT EXISTS idx_detalle_empleado ON detalle_liquidacion(id_empleado);

-- ==================== AGREGAR CAMPOS DE LIQUIDACIÓN A TABLAS EXISTENTES ====================
-- Turnos
ALTER TABLE turnos ADD COLUMN IF NOT EXISTS id_liquidacion INT;
ALTER TABLE turnos ADD COLUMN IF NOT EXISTS pagado BOOLEAN DEFAULT FALSE;

-- Horas Extra
ALTER TABLE horas_extra ADD COLUMN IF NOT EXISTS id_liquidacion INT;
ALTER TABLE horas_extra ADD COLUMN IF NOT EXISTS pagado BOOLEAN DEFAULT FALSE;

-- Foreign keys para id_liquidacion
ALTER TABLE turnos ADD CONSTRAINT IF NOT EXISTS fk_turnos_liquidacion 
    FOREIGN KEY (id_liquidacion) REFERENCES liquidaciones_nomina(id_liquidacion) ON DELETE SET NULL;
ALTER TABLE descuentos_nomina ADD CONSTRAINT IF NOT EXISTS fk_descuentos_liquidacion 
    FOREIGN KEY (id_liquidacion) REFERENCES liquidaciones_nomina(id_liquidacion) ON DELETE SET NULL;
ALTER TABLE horas_extra ADD CONSTRAINT IF NOT EXISTS fk_horas_extra_liquidacion 
    FOREIGN KEY (id_liquidacion) REFERENCES liquidaciones_nomina(id_liquidacion) ON DELETE SET NULL;
